-- $BEGIN
INSERT INTO mamba_fact_encounter_hts_card (encounter_id,
                                           client_id,
                                           encounter_date,
                                           family_member_accompanying_patient, other_specified_family_member,
                                           delivery_model, counselling_approach, hct_entry_point,
                                           community_testing_point, other_community_testing, anc_visit_number,
                                           other_care_entry_point, reason_for_testing, reason_for_testing_other_specify,
                                           special_category, other_special_category, hiv_first_time_tester,
                                           previous_hiv_tests_date, months_since_first_hiv_aids_symptoms,
                                           previous_hiv_test_results, referring_health_facility,
                                           no_of_times_tested_in_last_12_months, no_of_partners_in_the_last_12_months,
                                           partner_tested_for_hiv, partner_hiv_test_result,
                                           pre_test_counseling_done, counselling_session_type,
                                           current_hiv_test_result, hiv_syphilis_duo,
                                           consented_for_blood_drawn_for_testing, hiv_recency_result,
                                           hiv_recency_viral_load_results, hiv_recency_viral_load_qualitative,
                                           hiv_recency_sample_id, hts_fingerprint_captured,
                                           results_received_as_individual, results_received_as_a_couple,
                                           couple_results, tb_suspect, presumptive_tb_case_referred,
                                           prevention_services_received, other_prevention_services,
                                           has_client_been_linked_to_care, name_of_location_transferred_to,
                                           serial_number     ,
                                           client_at_risk_of_acquiring_hiv ,
                                           risk_profile          ,
                                           do_you_consent_for_an_hiv_test ,
                                           consent_date          ,
                                           hiv_test_1_kit        ,
                                           hiv_test_1_kit_results       ,
                                           hiv_test_2_kit           ,
                                           hiv_test_2_kit_results        ,
                                           hiv_test_3_kit       ,
                                           hiv_test_3_kit_results            ,
                                           sample_sent_to_reference_laboratory   ,
                                           client_screened_for_tb       ,
                                           art_no        ,
                                           received_prevention_services ,
                                           test_name        ,
                                           test_date )
SELECT a.encounter_id,
    a.client_id,
    a.encounter_datetime,
       family_member_accompanying_patient,
       other_specified_family_member,
       delivery_model,
       counselling_approach,
       hct_entry_point,
       community_testing_point,
       other_community_testing,
       anc_visit_number,
       other_care_entry_point,
       reason_for_testing,
       reason_for_testing_other_specify,
       special_category,
       other_special_category,
       hiv_first_time_tester,
       previous_hiv_tests_date,
       months_since_first_hiv_aids_symptoms,
       previous_hiv_test_results,
       referring_health_facility,
       no_of_times_tested_in_last_12_months,
       no_of_partners_in_the_last_12_months,
       partner_tested_for_hiv,
       partner_hiv_test_result,
       pre_test_counseling_done,
       counselling_session_type,
       current_hiv_test_result,
       hiv_syphilis_duo,
       consented_for_blood_drawn_for_testing,
       hiv_recency_result,
       hiv_recency_viral_load_results,
       hiv_recency_viral_load_qualitative,
       hiv_recency_sample_id,
       hts_fingerprint_captured,
       results_received_as_individual,
       results_received_as_a_couple,
       couple_results,tb_suspect,
       presumptive_tb_case_referred,
       prevention_services_received,
       other_prevention_services,
       has_client_been_linked_to_care,
       name_of_location_transferred_to,
       serial_number     ,
       client_at_risk_of_acquiring_hiv ,
       risk_profile          ,
       do_you_consent_for_an_hiv_test ,
       consent_date          ,
       hiv_test_1_kit        ,
       hiv_test_1_kit_results       ,
       hiv_test_2_kit           ,
       hiv_test_2_kit_results        ,
       hiv_test_3_kit       ,
       hiv_test_3_kit_results            ,
       sample_sent_to_reference_laboratory   ,
       client_screened_for_tb       ,
       art_no        ,
       received_prevention_services ,
       test_name        ,
       test_date

FROM mamba_flat_encounter_hts_card a left join mamba_flat_encounter_hts_card_1 b on a.encounter_id = b.encounter_id;
-- $END